exports.sessionValidator = (req, res, next) => {
    req.check('year', 'year is required').notEmpty();
    req.check('district', 'district is required').notEmpty();
    req.check('male1', 'male figure is required').notEmpty();
    req.check('female1', 'female figure is required').notEmpty();
    req.check('total1', 'total is required').notEmpty();
    req.check('male2', 'male figure is required').notEmpty();
    req.check('female2', 'female figure is required').notEmpty();
    req.check('total2', 'total is required').notEmpty();
    req.check('male3', 'male figure is required').notEmpty();
    req.check('female3', 'female figure is required').notEmpty();
    req.check('total3', 'total is required').notEmpty();
    req.check('male4', 'male figure is required').notEmpty();
    req.check('female4', 'female figure is required').notEmpty();
    req.check('total4', 'total is required').notEmpty();
    req.check('male5', 'male figure is required').notEmpty();
    req.check('female5', 'female figure is required').notEmpty();
    req.check('total5', 'total is required').notEmpty();
    req.check('male6', 'male figure is required').notEmpty();
    req.check('female6', 'female figure is required').notEmpty();
    req.check('total6', 'total is required').notEmpty();
    req.check('male7', 'male figure is required').notEmpty();
    req.check('female7', 'female figure is required').notEmpty();
    req.check('total7', 'total is required').notEmpty();
    req.check('male8', 'male figure is required').notEmpty();
    req.check('female8', 'female figure is required').notEmpty();
    req.check('total8', 'total is required').notEmpty();
    req.check('male9', 'male figure is required').notEmpty();
    req.check('female9', 'female figure is required').notEmpty();
    req.check('total9', 'total is required').notEmpty();
    req.check('male10', 'male figure is required').notEmpty();
    req.check('female10', 'female figure is required').notEmpty();
    req.check('total10', 'total is required').notEmpty();
    req.check('male11', 'male figure is required').notEmpty();
    req.check('female11', 'female figure is required').notEmpty();
    req.check('total11', 'total is required').notEmpty();
    req.check('male12', 'male figure is required').notEmpty();
    req.check('female12', 'female figure is required').notEmpty();
    req.check('total12', 'total is required').notEmpty();
    req.check('male13', 'male figure is required').notEmpty();
    req.check('female13', 'female figure is required').notEmpty();
    req.check('total13', 'total is required').notEmpty();
    req.check('male14', 'male figure is required').notEmpty();
    req.check('female14', 'female figure is required').notEmpty();
    req.check('total14', 'total is required').notEmpty();
    req.check('male15', 'male figure is required').notEmpty();
    req.check('female15', 'female figure is required').notEmpty();
    req.check('total15', 'total is required').notEmpty();
    req.check('male16', 'male figure is required').notEmpty();
    req.check('female16', 'female figure is required').notEmpty();
    req.check('total16', 'total is required').notEmpty();
    req.check('male17', 'male figure is required').notEmpty();
    req.check('female17', 'female figure is required').notEmpty();
    req.check('total17', 'total is required').notEmpty();
    req.check('male18', 'male figure is required').notEmpty();
    req.check('female18', 'female figure is required').notEmpty();
    req.check('total18', 'total is required').notEmpty();
    req.check('male19', 'male figure is required').notEmpty();
    req.check('female19', 'female figure is required').notEmpty();
    req.check('total19', 'total is required').notEmpty();
    req.check('male20', 'male figure is required').notEmpty();
    req.check('female20', 'female figure is required').notEmpty();
    req.check('total20', 'total is required').notEmpty();
    req.check('male21', 'male figure is required').notEmpty();
    req.check('female21', 'female figure is required').notEmpty();
    req.check('total21', 'total is required').notEmpty();
    
    const errors = req.validationErrors();
    if (errors) {
        const firstError = errors.map(error => error.msg)[0];
        return res.status(400).json({ error: firstError });
    }
    next();
};