import mongoose from 'mongoose';
const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');
const {ObjectId} = mongoose.Schema;
const Schema = mongoose.Schema;

const populationSchema = mongoose.Schema({
    year:{
        type:Date,
        require:true
    },
    male1:{
        type:Number,
        require:true
    },
    female1:{
        type:Number,
        require:true
    },
    total1:{
        type:Number,
        require:true
    },
    district:{
        type: Schema.Types.ObjectId,
        ref: "District",
        required: true,
    },
    male2:{
        type:Number,
        require:true
    },
    female2:{
        type:Number,
        require:true
    },
    total2:{
        type:Number,
        require:true
    },
    male3:{
        type:Number,
        require:true
    },
    female3:{
        type:Number,
        require:true
    },
    total3:{
        type:Number,
        require:true
    },
    male4:{
        type:Number,
        require:true
    },
    female4:{
        type:Number,
        require:true
    },
    total4:{
        type:Number,
        require:true
    },
    male5:{
        type:Number,
        require:true
    },
    female5:{
        type:Number,
        require:true
    },
    total5:{
        type:Number,
        require:true
    },
    male6:{
        type:Number,
        require:true
    },
    female6:{
        type:Number,
        require:true
    },
    total6:{
        type:Number,
        require:true
    },
    male7:{
        type:Number,
        require:true
    },
    female7:{
        type:Number,
        require:true
    },
    total7:{
        type:Number,
        require:true
    },
    male8:{
        type:Number,
        require:true
    },
    female8:{
        type:Number,
        require:true
    },
    total8:{
        type:Number,
        require:true
    },
    male9:{
        type:Number,
        require:true
    },
    female9:{
        type:Number,
        require:true
    },
    total9:{
        type:Number,
        require:true
    },
    male10:{
        type:Number,
        require:true
    },
    female10:{
        type:Number,
        require:true
    },
    total10:{
        type:Number,
        require:true
    },
    male11:{
        type:Number,
        require:true
    },
    female11:{
        type:Number,
        require:true
    },
    total11:{
        type:Number,
        require:true
    },
    male12:{
        type:Number,
        require:true
    },
    female12:{
        type:Number,
        require:true
    },
    total12:{
        type:Number,
        require:true
    },
    male13:{
        type:Number,
        require:true
    },
    female13:{
        type:Number,
        require:true
    },
    total13:{
        type:Number,
        require:true
    },
    male14:{
        type:Number,
        require:true
    },
    female14:{
        type:Number,
        require:true
    },
    total14:{
        type:Number,
        require:true
    },
    male15:{
        type:Number,
        require:true
    },
    female15:{
        type:Number,
        require:true
    },
    total15:{
        type:Number,
        require:true
    },
    male16:{
        type:Number,
        require:true
    },
    female16:{
        type:Number,
        require:true
    },
    total16:{
        type:Number,
        require:true
    },
    male17:{
        type:Number,
        require:true
    },
    female18:{
        type:Number,
        require:true
    },
    total18:{
        type:Number,
        require:true
    },
    male1:{
        type:Number,
        require:true
    },
    female19:{
        type:Number,
        require:true
    },
    total19:{
        type:Number,
        require:true
    },
    male20:{
        type:Number,
        require:true
    },
    female20:{
        type:Number,
        require:true
    },
    total20:{
        type:Number,
        require:true
    },
    male21:{
        type:Number,
        require:true
    },
    female21:{
        type:Number,
        require:true
    },
    total21:{
        type:Number,
        require:true
    },
    male22:{
        type:Number,
        //require:true
    },
    female22:{
        type:Number,
        //require:true
    },
    total22:{
        type:Number,
       // require:true
    },
    male23:{
        type:Number,
        //require:true
    },
    female23:{
        type:Number,
        //require:true
    },
    total23:{
        type:Number,
       // require:true
    },

})

module.exports = mongoose.model('Population', populationSchema)